[package]
name    = "neoutl-effect-displacement-map-image"
version = "0.0.0"
edition = "2024"

[lib]
name       = "neoutl_effect_displacement_map_image"
crate-type = ["cdylib"]

[dependencies]
rust-i18n.workspace = true
neoutl-effect-api = { path = "../../neoutl-effect-api" }

[build-dependencies]
neoutl-effect-shader-build.workspace = true
