[package]
name = "neoutl-easing-standard"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
neoutl-easing-api.workspace = true
neoutl-shared-abi.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
mlua.workspace = true

[build-dependencies]
