[package]
name    = "neoutl-effect-lua"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
rust-i18n.workspace = true
neoutl-shared-abi = { path = "../neoutl-shared-abi" }
neoutl-effect-api = { path = "../neoutl-effect-api" }
mlua = { version = "0.12", default-features = false, features = ["vendored", "send"] }

[features]
default = []
luajit = ["mlua/luajit"]
lua54 = ["mlua/lua54"]
