[package]
name = "neoutl-audio-plugin-host"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-i18n.workspace = true
vst3-host = "0.9"
clack-host = { version = "0.1", features = ["libloading"] }
clack-common = "0.1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
clack-extensions = { version = "0.1", features = ["params"] }
clap-sys = "0.5"
