[package]
name    = "neoutl-lua-runtime"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
rust-i18n.workspace = true
neoutl-shared-abi = { path = "../neoutl-shared-abi" }
neoutl-effect-lua = { path = "../neoutl-effect-lua" }
mlua = { version = "0.12", default-features = false, features = ["vendored", "send"] }

# （defaultを空にすることで、[target.'cfg(...)']による自動切替がCargoのfeature統一で
[features]
default = []
luajit = ["mlua/luajit"]
lua54 = ["mlua/lua54"]
