[package]
name = "neoutl-media-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
neoutl-media-api.workspace = true
neo-media-ffmpeg.workspace = true
egui-wgpu = "0.36"
wgpu_text.workspace = true
arc-swap.workspace = true
libloading.workspace = true
tokio.workspace = true
rust-i18n.workspace = true
