[package]
name = "NeoQtl"
version = "0.0.0"
edition = "2024"

[dependencies]
cxx = "1"
cxx-qt = "0.10"
cxx-qt-lib = { version = "0.10", features = ["qt_full"] }
neoutl-shared-abi = { path = "../crates/neoutl-shared-abi" }
neoutl-color = { path = "../crates/neoutl-color" }
bytemuck = "1"
half = "2"
neoutl-object-api = { path = "../crates/neoutl-object-api" }
neoutl-effect-api = { path = "../crates/neoutl-effect-api" }
neoutl-effect-lua = { path = "../crates/neoutl-effect-lua" }
neoutl-lua-runtime = { path = "../crates/neoutl-lua-runtime" }
neoutl-easing-api = { path = "../crates/neoutl-easing-api" }
neoutl-expression-api = { path = "../crates/neoutl-expression-api" }
neoutl-media-api = { path = "../crates/neoutl-media-api" }
neoutl-media-runtime = { path = "../crates/neoutl-media-runtime" }
neoutl-mlt-api = { path = "../crates/neoutl-mlt-api" }
neoutl-easing-standard = { path = "../crates/easings/neoutl-easing-standard" }
neoutl-schema = { path = "../crates/neoutl-schema" }
prost = "0.14"
prost-types = "0.14"
toml = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
libloading = "0.9"
arc-swap = "1"
notify = "8"
rodio = { version = "0.22", default-features = false, features = ["playback", "symphonia-wav", "symphonia-mp3", "symphonia-vorbis", "symphonia-flac", "symphonia-aac", "symphonia-isomp4"] }
neo-media-ffmpeg = { path = "../crates/neo-media-ffmpeg" }
self-replace = "1"
sentry = { version = "0.49", default-features = false, features = ["backtrace", "contexts", "panic"] }
semver = "1"
tempfile = "3"
wgpu = "30"
wgpu_text = "30"
font-kit = "0.14"
tokio = { version = "1", features = ["rt-multi-thread", "sync"] }
shipyard = "0.11"
rfd = "0.17"
pollster = "1"
rust-i18n = "4"
ureq = { version = "3", features = ["json", "_tls"] }
zip = "8"
maolan-host-adapter = { path = "../crates/maolan-host-adapter" }
winit = { version = "0.30", features = ["rwh_06", "x11"] }
raw-window-handle = "0.6"


[build-dependencies]
cxx-build = "1"
cxx-qt-build = "0.10"
neoutl-object-shader-build = { path = "../crates/neoutl-object-shader-build" }
cc = "1"

