pub const PROJECT_DEFAULT_WIDTH: u32 = 1920;
pub const PROJECT_DEFAULT_HEIGHT: u32 = 1080;
pub const PROJECT_DEFAULT_FPS: u32 = 30;
pub const PROJECT_DEFAULT_AUDIO_SAMPLE_RATE: u32 = 48_000;
pub const PROJECT_DEFAULT_AUDIO_CHANNELS: u32 = 2;

pub const DEFAULT_LAYER_COUNT: usize = 128;
pub const DEFAULT_TOTAL_FRAMES: i32 = 300;

pub const SCENE_DEFAULT_GRID_INTERVAL: i32 = 10;
pub const SCENE_DEFAULT_GRID_SUBDIVISION: i32 = 4;
pub const SCENE_DEFAULT_GRID_BPM: f32 = 120.0;
pub const SCENE_DEFAULT_GRID_OFFSET: f32 = 0.0;
pub const SCENE_DEFAULT_ENABLE_SNAP: bool = true;
pub const SCENE_DEFAULT_MAGNETIC_SNAP_RANGE: i32 = 10;

pub const SYSTEM_DEFAULT_AUTOSAVE_ENABLED: bool = true;
pub const SYSTEM_DEFAULT_AUTOSAVE_INTERVAL_SEC: i32 = 300;
pub const SYSTEM_DEFAULT_THEME_DARK: bool = true;
pub const SYSTEM_DEFAULT_THEME_ID: &str = "";
pub const SYSTEM_DEFAULT_EASING_ENGINE_ID: &str = "neoutl-easing-standard";
pub const SYSTEM_DEFAULT_UI_SCALE_PERCENT: i32 = 100;
pub const SYSTEM_DEFAULT_WORKER_THREADS: i32 = 0;
pub const SYSTEM_DEFAULT_AUDIO_MAX_BLOCK_SIZE: i32 = 4096;
pub const SYSTEM_DEFAULT_DECODE_BACKEND: i32 = DECODE_BACKEND_AUTO;
pub const SYSTEM_DEFAULT_DEFAULT_SNAP: bool = true;
pub const SYSTEM_DEFAULT_MAGNETIC_SNAP_RANGE: i32 = 10;
pub const SYSTEM_DEFAULT_CHECK_UPDATE_ON_STARTUP: bool = false;
pub const SYSTEM_DEFAULT_CRASH_REPORTING_ENABLED: bool = false;
pub const SYSTEM_DEFAULT_MAX_GROUP_CHAIN_DEPTH: i32 = 32;
pub const SYSTEM_DEFAULT_HW_DECODE_EXTRA_FRAMES: i32 = 16;
pub const HW_DECODE_EXTRA_FRAMES_MIN: i32 = 4;
pub const HW_DECODE_EXTRA_FRAMES_MAX: i32 = 64;
pub const SENTRY_DSN: &str = "https://a5c5db74531842109880e0e97e054915@app.glitchtip.com/26533";
pub const SYSTEM_DEFAULT_HOT_RELOAD_ENABLED: bool = cfg!(debug_assertions);

pub const DECODE_BACKEND_AUTO: i32 = 0;
pub const DECODE_BACKEND_GPU_FIXED: i32 = 1;
pub const DECODE_BACKEND_CPU_FIXED: i32 = 2;

pub const UNDO_HISTORY_LIMIT: usize = 100;

pub const DECODE_RING_CAPACITY: usize = neoutl_media_api::VIDEO_TEXTURE_POOL_CAPACITY;
pub const DECODE_PREFETCH_RADIUS: i64 = 8;
const _: () = assert!(DECODE_RING_CAPACITY as i64 > DECODE_PREFETCH_RADIUS * 2);

pub const MAX_SCENE_OBJECTS: u64 = 512;

pub const MAX_SCENE_NESTING_DEPTH: u32 = 8;
pub const UNIFORM_STRIDE_BYTES: u64 = 256;
pub const MAX_EFFECT_UNIFORM_BYTES: u64 = 128;

pub const MAX_EFFECT_OBJECTS: usize = 64;

pub const PLAYBACK_SPEED_MIN_PERCENT: i32 = 10;
pub const PLAYBACK_SPEED_MAX_PERCENT: i32 = 400;
