[package]
name = "neoutl-media-ffmpeg-decoder"
version = "0.0.0"
edition = "2024"

[dependencies]
neoutl-media-api = { path = "../../neoutl-media-api" }
ffmpeg-next = { version = "9", features = ["codec", "format", "software-resampling"] }
ffmpeg-sys-next = { version = "9", features = ["swscale"] }
libc = "0.2"
wgpu = { version = "29", features = ["vulkan-portability"] }
wgpu-hal = { version = "29", features = ["vulkan"] }
ash = "0.38"

[build-dependencies]
neoutl-object-shader-build.workspace = true
