[package]
name = "neoutl-media-ffmpeg-decoder"
version = "0.0.0"
edition = "2024"

[dependencies]
neoutl-media-api = { path = "../../neoutl-media-api" }
ffmpeg-next = { version = "9", features = ["codec", "format", "software-resampling"] }
ffmpeg-sys-next = "9"
wgpu = { version = "29", features = ["vulkan-portability"] }
wgpu-hal = "29"
ash = "0.38"
