[package]
name = "neoutl-media-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
neoutl-media-api.workspace = true
neo-media-ffmpeg = { path = "../neo-media-ffmpeg" }
egui-wgpu = "0.36"
wgpu_text = "30"
arc-swap = "1"
libloading = "0.9"
tokio = { version = "1", features = ["rt-multi-thread", "sync"] }
rust-i18n.workspace = true
