[package]
name = "neoutl-media-gstreamer-encoder"
version = "0.0.0"
edition = "2024"

[lib]
name       = "neoutl_media_gstreamer_encoder"
crate-type = ["cdylib", "rlib"]

[dependencies]
rust-i18n.workspace = true
neoutl-media-api = { path = "../../neoutl-media-api" }
gstreamer = "0.25"
gstreamer-app = "0.25"
gstreamer-pbutils = "0.25"
bytemuck = { version = "1", features = ["derive"] }
