name: Build and Release Linux (x86_64)

on:
  push:
    tags:
      - '**'

permissions:
  contents: write

jobs:
  build-linux:
    name: Linux (x86_64)
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize Pacman Keys and Install Runner Dependencies
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Sy --noconfirm archlinux-keyring
          pacman -S --needed --noconfirm \
            base-devel git cmake ninja clang mold zip mesa vulkan-devel \
            libxkbcommon wayland wayland-protocols libffi ffmpeg luajit fftw \
            qt6-base qt6-declarative qt6-quick3d qt6-multimedia qt6-shadertools \
            qt6-svg qt6-5compat qt6-tools lilv ladspa carla openmp \
            extra-cmake-modules libc++ fluidsynth \
            pyside6 sudo ccache

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 500M
          key: linux-ccache

      - name: Build and Package
        run: python3 BUILD.py --arch --no-container

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AviQtl-Arch-Linux-x86_64
          path: dist/AviQtl-Arch-Linux-x86_64.zip
          retention-days: 1
          if-no-files-found: error

      - name: Create Codeberg Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: akkuman/gitea-release-action@v1
        with:
          server_url: https://codeberg.org
          token: ${{ secrets.CODEBERG_TOKEN }}
          repository: taisho-guy/AviQtl
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ""
          files: |
            dist/AviQtl-Arch-Linux-x86_64.zip