name: Build and Release Windows (x86_64)

on:
  push:
    tags:
      - '**'

permissions:
  contents: write

jobs:
  build-windows:
    name: Windows (x86_64)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          cache: true
          install: >-
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja
            python
            mingw-w64-ucrt-x86_64-pyside6
            zip

      - name: Build and Package
        run: python3 BUILD.py --msys2

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AviQtl-MSYS2-UCRT64-x86_64
          path: dist/AviQtl-MSYS2-UCRT64-x86_64.zip
          retention-days: 1
          if-no-files-found: error

      - name: Create Codeberg Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: akkuman/gitea-release-action@v1
        env:
          GITEA_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        with:
          server_url: https://codeberg.org
          token: ${{ secrets.CODEBERG_TOKEN }}
          repository: taisho-guy/AviQtl
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ""
          files: |
            dist/AviQtl-MSYS2-UCRT64-x86_64.zip

      - name: Delete GitHub Actions Artifact
        if: success()
        uses: geekyeggo/delete-artifact@v2
        with:
          name: AviQtl-MSYS2-UCRT64-x86_64